FROM r.gpxtrade.com/mhart/alpine-node
COPY repositories /etc/apk/repositories
RUN apk add --no-cache ca-certificates tzdata && cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
  && echo "Asia/Shanghai" >  /etc/timezone && date && apk --no-cache del tzdata
COPY npmrc /root/.npmrc
